Bahmni/bahmni-docker

- bahmni-proxy/Dockerfile
- bahmni-proxy/resources/bahmni-proxy.conf
Renamed and moved mod_wsgi module to apache2 modules
> BAH-2535 | Fix | Proxy container errors on Mac M1 chip machines

- .env
- README.md
- docker-compose.yml
Metabase should be integrated with Bahmni Docker with its own Database so that we can run Metabase from Bahmni Docker.
JIRA Ticket - https://bahmni.atlassian.net/browse/BAH-2580
> BAH-2580 | Dockerizing metabase with its own Database

- docker-compose.yml
JIRA - https://bahmni.atlassian.net/browse/BS-38
Command used to bring up the environment - `docker compose --profile snomed up -d`
> BS-38 | Adding new profile for SNOMED

- .env
JIRA - https://bahmni.atlassian.net/browse/BS-39
> BS-39 | Siva, Vijay | using SNOMED related docker images

- bahmni-lite/docker-compose.yml
- Adds volume mounts for configuration_checksums
- [Documentation](https://bahmni.atlassian.net/wiki/spaces/BAH/pages/3117744129/Getting+Started+Quickly+with+Bahmni+on+Docker#Running-Bahmni-Lite)
Co-authored-by: Kavitha S <kavitha.s@thoughtworks.com>
> BAH-2668 | Bahmni Lite openmrs DB snapshot image for local development

- bahmni-lite/.env
- bahmni-lite/docker-compose.yml
JIRA Card -> [https://bahmni.atlassian.net/browse/BAH-2736](https://bahmni.atlassian.net/browse/BAH-2736)
> Bindu | BAH-2736 | make clinic config db as the default db

- bahmni-proxy/resources/bahmni-proxy.conf
- bahmni-standard/.env
- bahmni-standard/docker-compose.yml
The docker-compose.yaml file in the Bahmni Docker should be updated to include the Bahmni-Mart Application and the decided dependencies, so that every time we perform a docker-compose up along with the rest of the Bahmni Application the Bahmni-Mart should also be started.
-----------
https://bahmni.atlassian.net/browse/BAH-2586
> BAH-2586 | Bahmni-Mart Application with Bahmni Docker

- bahmni-lite/docker-compose.yml
- bahmni-standard/docker-compose.yml
…. Also added some missing services into emr profile - like lablite and implementer interface
> BAH-2791: Ensure that when mart/metabase are chosen, the right services come up

- README.md
- bahmni-lite/run-bahmni.sh
- bahmni-standard/run-bahmni.sh
- run-bahmni.sh
Added a utility wrapper script for making it easy for new users to use docker compose. This script also checks if docker is installed, and min version of docker. It will only run from subfolders bahmni-lite or bahmni-standard. 
Sample output:
> Bah-2794: Added a run-bahmni.sh script for common docker compose commands, for making life easy!

- bahmni-lite/docker-compose.yml
- bahmni-standard/docker-compose.yml
JIRA Link - https://bahmni.atlassian.net/browse/BAH-2791
> BAH-2791 Added bahmni-mart profile to bahmni-web

- run-bahmni.sh
For ./run-Bahmni.sh, added ability to restart a docker compose service. 
1. Note: restart command only works for profile mentinoed in .env. So, it won't  restart metabase service, if current profile in .env file doesn't include it.
2. Modified the status prints to print ALL running services. (across profiles).
3. Minor message enhancements for accuracy.
> BAH-2802|Gurpreet|Added ability to restart a compose service

- .github/workflows/snomed-deploy.yml
JIRA - https://bahmni.atlassian.net/browse/BS-42
> Siva Reddy | BS-42 | deployment to SNOMED Environment

- bahmni-proxy/Dockerfile
- bahmni-standard/docker-compose.yml
- Adds volume mounts to openelis service and proxy service
- Added command to disable directory indexing
> BAH-2899 | Add volume mounts for OpenELIS uploaded results directory

- .env
- docker-compose.yml
JIRA https://bahmni.atlassian.net/browse/BS-100
> Siva Reddy | BS-100 | Adding CDSS docker image

- bahmni-lite/.env
This PR fixes the OpenMRS database backup image name
> Fix. OpenMRS Database backup image name

- backups/README.md
- backups/backup.sh
- backups/restore.sh
Co-authored by: Riya Kumari, Deepti Rawat
> #BAH-3019 | Add. Backup and Restore Scripts for Bahmni databases and files

- .github/workflows/bahmni_lite_docker_env.yaml
- .github/workflows/bahmni_standard_docker_env.yaml
- bahmni-lite/.env
- bahmni-lite/.env.dev
- bahmni-standard/.env.dev
jira card -> https://bahmni.atlassian.net/browse/BAH-3068
In this PR, the IMAGE_TAGS in .env file in bahmni-lite is updated to latest.
> Parvathy | Update docker image tags to latest

- bahmni-lite/docker-compose.yml
- bahmni-standard/docker-compose.yml
Adds a volume mount to persist reports database data
> BAH-3383 | Add missing volumes for reports database

- .github/workflows/scan_images.yaml
https://bahmni.atlassian.net/browse/BAH-3835
> BAH-3835 | Update workflow to commit text report formats

- bahmni-standard/backup_bahmni_standard.sh
- bahmni-standard/restore_bahmni_standard.sh
This PR extends the bahmni-standard backup and restore scripts for Odoo 10 Database.
JIRA: https://bahmni.atlassian.net/browse/BAH-4038
> BAH-4038 | Add. Backup and restore commands for Odoo 10 database
